POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "jedybrown9821@gmail.com",
    "password": "Password2#"
}

###
GET http://localhost:5000/classroom.html
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJPZ2FTb2xvIiwiaWF0IjoxNzIwNDQxNjQ2LCJleHAiOjE3MjA0NDg4NDZ9.Y-eCHzH0BsAsDVeCxakbteSf041M6gBdEuTRc8FsE3E
### https://fusionauth.io/dev-tools/jwt-decoder